alias vim='nvim'
alias vimrc='nvim ~/.vimrc'
#alias vimrc='nvim ~/.config/nvim/init.vim'
alias neofetch='fastfetch'

alias bashrc='nvim ~/.bashrc && source ~/.bashrc'
alias bashalias='nvim ~/.bash_aliases && source ~/.bash_aliases'
alias bashprofile='nvim ~/.bash_profile'

alias i3conf='nvim ~/.config/i3/config'
alias i3configstatus='nvim ~/.i3status.conf'
alias i3resources='nvim ~/.Xresources'

alias pac='sudo pacman -Syu'
alias pacr='sudo pacman -Rns'
alias pacq='pacman -Qdtq'
alias pacrr='sudo pacman -Qdtq | sudo pacman -Rns -'
alias pacss='pacman -Ss'
alias yayr='yay -Rns'
alias yayq='yay -Qdtq'
alias yayrr='yay -Qdtq | yay -Rns -'
alias yayss='yay -Ss'
